name: Build and Test - Classroom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y build-essential default-jdk nasm gdb vim \
                              python3-pip ninja-build libglib2.0-dev libpixman-1-dev meson \
                              curl git htop jq locales sudo tzdata wget
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib libc6:i386 libc6-dev-i386
          sudo apt install -y gcc-riscv64-unknown-elf gcc-riscv64-linux-gnu qemu-user
          pip install tomli

      - name: Verify toolchain
        run: |
          gcc --version
          gcc -m32 --version
          nasm -v
          qemu-riscv64 --version || true
          riscv64-unknown-elf-gcc --version || true
          riscv64-linux-gnu-gcc --version || true

      - name: Build project
        run: make

      - name: Compare tests against template version
        run: |
          if ! diff <(curl -s https://raw.githubusercontent.com/CaoilfhionnNiD/CSU34021-ComputerArchitecture-Project2/main/run_test.sh) run_test.sh; then
            echo "ERROR: run_test.sh has been modified. Autograder will not run."
            exit 1
          fi

      - name: Compare expected output files against template version
        run: |
          for file in expected_output/*; do
            if ! diff <(curl -s https://raw.githubusercontent.com/CaoilfhionnNiD/CSU34021-ComputerArchitecture-Project2/main/$file) $file; then
              echo "ERROR: $file has been modified. Autograder will not run."
              exit 1
            fi
          done

      - name: Compare GitHub Actions workflow file against template version
        run: |
          if ! diff <(curl -s https://raw.githubusercontent.com/CaoilfhionnNiD/CSU34021-ComputerArchitecture-Project2/main/.github/workflows/classroom.yml) .github/workflows/classroom.yml; then
            echo "ERROR: .github/workflows/classroom.yml has been modified. Autograder will not run."
            exit 1
          fi

      - name: Run autograder
        run: bash run_test.sh
